name: "Run tests"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  guard_manual_run:
    uses: ./.github/workflows/guard-manual.yml
    with:
      is_manual: ${{ github.event_name == 'workflow_dispatch' }}
      actor: ${{ github.actor }}
      allowed: "ydkmlt84"

  run_tests:
    name: Run integration tests
    needs: guard_manual_run
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Activate corepack
        run: |
          corepack install
          corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn turbo build --filter="./packages/*"

      - name: Run tests
        run: yarn turbo test
