name: Close inactive issues
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:

jobs:
  guard_manual_run:
    uses: ./.github/workflows/guard-manual.yml
    with:
      is_manual: ${{ github.event_name == 'workflow_dispatch' }}
      actor: ${{ github.actor }}
      allowed: "ydkmlt84"

  close-issues:
    needs: guard_manual_run
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          exempt-issue-labels: never-stale,bug,enhancement
          exempt-issue-assignees: jorenn92,ydkmlt84
          stale-issue-label: "stale"
          close-issue-label: "stale-closed"
          stale-issue-message: "This issue has been marked stale because it has been 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          debug-only: false
